In [16]:
import numpy as np


In [17]:
# Q1

# (a)
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Q1(a):", reversed_arr)

Q1(a): [5 4 6 3 2 1]


In [18]:
# (b)
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened_1 = array1.flatten()
flattened_2 = array1.ravel()
print("Q1(b) Method 1:", flattened_1)
print("Q1(b) Method 2:", flattened_2)


Q1(b) Method 1: [1 2 3 2 4 5 1 2 3]
Q1(b) Method 2: [1 2 3 2 4 5 1 2 3]


In [19]:
#(c)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
comparison = np.array_equal(arr1, arr2)
element_wise = arr1 == arr2
print("Q1(c) Arrays equal:", comparison)
print("Q1(c) Element-wise:", element_wise)

Q1(c) Arrays equal: True
Q1(c) Element-wise: [[ True  True]
 [ True  True]]


In [20]:
# (d)
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

unique_x, counts_x = np.unique(x, return_counts=True)
most_frequent_x = unique_x[np.argmax(counts_x)]
indices_x = np.where(x == most_frequent_x)[0]
print("Q1(d)i Most frequent in x:", most_frequent_x, "Indices:", indices_x)

unique_y, counts_y = np.unique(y, return_counts=True)
most_frequent_y = unique_y[np.argmax(counts_y)]
indices_y = np.where(y == most_frequent_y)[0]
print("Q1(d)ii Most frequent in y:", most_frequent_y, "Indices:", indices_y)

Q1(d)i Most frequent in x: 1 Indices: [0 5 7 8 9]
Q1(d)ii Most frequent in y: 1 Indices: [0 1 2]


In [21]:
# (e)
gfg = np.matrix('4, 1, 9; 12, 3, 1; 4, 5, 6')
sum_all = np.sum(gfg)
sum_rows = np.sum(gfg, axis=1)
sum_cols = np.sum(gfg, axis=0)
print("Q1(e)i Sum of all elements:", sum_all)
print("Q1(e)ii Sum row-wise:", sum_rows.flatten())
print("Q1(e)iii Sum column-wise:", sum_cols.flatten())

Q1(e)i Sum of all elements: 45
Q1(e)ii Sum row-wise: [[14 16 15]]
Q1(e)iii Sum column-wise: [[20  9 16]]


In [22]:
# (f)
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
diag_sum = np.trace(n_array)
eigenvalues, eigenvectors = np.linalg.eig(n_array)
inverse_matrix = np.linalg.inv(n_array)
determinant = np.linalg.det(n_array)
print("Q1(f)i Sum of diagonal:", diag_sum)
print("Q1(f)ii Eigenvalues:", eigenvalues)
print("Q1(f)iii Eigenvectors:", eigenvectors)
print("Q1(f)iv Inverse:", inverse_matrix)
print("Q1(f)v Determinant:", determinant)

Q1(f)i Sum of diagonal: 176
Q1(f)ii Eigenvalues: [98.16835147 28.097044   49.73460452]
Q1(f)iii Eigenvectors: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Q1(f)iv Inverse: [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Q1(f)v Determinant: 137180.0000000001


In [23]:
# (g)
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
mult_1 = np.dot(p1, q1)
cov_1 = np.cov(p1.flatten(), q1.flatten())
print("Q1(g)i Multiplication:", mult_1)
print("Q1(g)i Covariance:", cov_1)

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
mult_2 = np.dot(p2, q2)
cov_2 = np.cov(p2.flatten(), q2.flatten())
print("Q1(g)ii Multiplication:", mult_2)
print("Q1(g)ii Covariance:", cov_2)

Q1(g)i Multiplication: [[16 19]
 [26 31]]
Q1(g)i Covariance: [[0.66666667 1.        ]
 [1.         1.66666667]]
Q1(g)ii Multiplication: [[16 19  5]
 [26 31  8]
 [46 55 14]]
Q1(g)ii Covariance: [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [24]:
# (h)
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner_prod = np.inner(x, y)
outer_prod = np.outer(x, y)
cartesian_prod = np.cross(x, y)
print("Q1(h) Inner product:", inner_prod)
print("Q1(h) Outer product:", outer_prod)
print("Q1(h) Cartesian product:", cartesian_prod)

Q1(h) Inner product: [[17 52]
 [13 62]]
Q1(h) Outer product: [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Q1(h) Cartesian product: [[-20   4   7]
 [-84  36  20]]


In [25]:
# Q2

# (a)
array = np.array([[1, -2, 3],[-4, 5, -6]])
abs_array = np.abs(array)
print("Q2(a)i Absolute values:", abs_array)

flattened = array.flatten()
perc_25_flat = np.percentile(flattened, 25)
perc_50_flat = np.percentile(flattened, 50)
perc_75_flat = np.percentile(flattened, 75)
print("Q2(a)ii Percentiles (flattened) - 25th:", perc_25_flat, "50th:", perc_50_flat, "75th:", perc_75_flat)

perc_25_col = np.percentile(array, 25, axis=0)
perc_50_col = np.percentile(array, 50, axis=0)
perc_75_col = np.percentile(array, 75, axis=0)
print("Q2(a)ii Percentiles (columns) - 25th:", perc_25_col, "50th:", perc_50_col, "75th:", perc_75_col)

perc_25_row = np.percentile(array, 25, axis=1)
perc_50_row = np.percentile(array, 50, axis=1)
perc_75_row = np.percentile(array, 75, axis=1)
print("Q2(a)ii Percentiles (rows) - 25th:", perc_25_row, "50th:", perc_50_row, "75th:", perc_75_row)

mean_flat = np.mean(flattened)
median_flat = np.median(flattened)
std_flat = np.std(flattened)
print("Q2(a)iii Flattened - Mean:", mean_flat, "Median:", median_flat, "Std:", std_flat)

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)
print("Q2(a)iii Columns - Mean:", mean_col, "Median:", median_col, "Std:", std_col)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)
print("Q2(a)iii Rows - Mean:", mean_row, "Median:", median_row, "Std:", std_row)

Q2(a)i Absolute values: [[1 2 3]
 [4 5 6]]
Q2(a)ii Percentiles (flattened) - 25th: -3.5 50th: -0.5 75th: 2.5
Q2(a)ii Percentiles (columns) - 25th: [-2.75 -0.25 -3.75] 50th: [-1.5  1.5 -1.5] 75th: [-0.25  3.25  0.75]
Q2(a)ii Percentiles (rows) - 25th: [-0.5 -5. ] 50th: [ 1. -4.] 75th: [2.  0.5]
Q2(a)iii Flattened - Mean: -0.5 Median: -0.5 Std: 3.8622100754188224
Q2(a)iii Columns - Mean: [-1.5  1.5 -1.5] Median: [-1.5  1.5 -1.5] Std: [2.5 3.5 4.5]
Q2(a)iii Rows - Mean: [ 0.66666667 -1.66666667] Median: [ 1. -4.] Std: [2.05480467 4.78423336]


In [26]:
# (b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_vals = np.floor(a)
ceil_vals = np.ceil(a)
trunc_vals = np.trunc(a)
round_vals = np.round(a)
print("Q2(b) Floor:", floor_vals)
print("Q2(b) Ceiling:", ceil_vals)
print("Q2(b) Truncated:", trunc_vals)
print("Q2(b) Rounded:", round_vals)

Q2(b) Floor: [-2. -2. -1.  0.  1.  1.  3.]
Q2(b) Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Q2(b) Truncated: [-1. -1. -0.  0.  1.  1.  3.]
Q2(b) Rounded: [-2. -2. -0.  0.  2.  2.  3.]


In [27]:
# Q3:

# (a)
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
sorted_indices = np.argsort(array)
smallest_4 = np.partition(array, 3)[:4]
largest_5 = np.partition(array, -5)[-5:]
print("Q3(a)i Sorted array:", sorted_array)
print("Q3(a)ii Sorted indices:", sorted_indices)
print("Q3(a)iii 4 smallest:", np.sort(smallest_4))
print("Q3(a)iv 5 largest:", np.sort(largest_5))

Q3(a)i Sorted array: [ 10  16  16  52  54  62 453]
Q3(a)ii Sorted indices: [0 3 4 1 5 2 6]
Q3(a)iii 4 smallest: [10 16 16 52]
Q3(a)iv 5 largest: [ 16  52  54  62 453]


In [28]:
# (b)
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integer_elements = array[array == array.astype(int)]
float_elements = array[array != array.astype(int)]
print("Q3(b)i Integer elements:", integer_elements)
print("Q3(b)ii Float elements:", float_elements)

Q3(b)i Integer elements: [1. 2. 3. 2.]
Q3(b)ii Float elements: [1.2 2.2]
